services:
  mysql:
    image: mysql:8
    environment:
      - 'MYSQL_DATABASE=rem_db'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=rem123'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio
    restart: unless-stopped

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 123456

    volumes:
      - /mnt/minio:/data

    command: server /data --console-address ":9001"

volumes:
  mysql_data:
  minio_data: