services:
  mysql:
    image: 'mysql:9.6.0'
    environment:
      - 'MYSQL_DATABASE=rem_db'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=rem123'
    ports:
      - '3300:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  rem-server:
    image: 'tien1411/rem-server:latest'
    ports:
      - '3002:8080'

volumes:
  mysql_data: