CREATE TABLE `businesses` (
    `id` VARCHAR(24) NOT NULL,
    `created_at` DATETIME(6) NULL,
    `updated_at` DATETIME(6) NULL,
    `owner_user_id` VARCHAR(24) NOT NULL,
    `description` VARCHAR(255) NULL,
    `name` VARCHAR(100) NOT NULL,
    `slug` VARCHAR(100) NULL,
    `logo_url` VARCHAR(255) NULL,
    `work_start_time` TIME(6) NULL,
    `insurance_contribution_salary` INT NULL,
    `twilio_account_sid` VARCHAR(255) NULL,
    `twilio_auth_token` VARCHAR(255) NULL,
    `twilio_phone_number` VARCHAR(255) NULL,
    `vonage_api_key` VARCHAR(255) NULL,
    `vonage_api_secret` VARCHAR(255) NULL,
    `cloudinary_cloud_name` VARCHAR(255) NULL,
    `cloudinary_api_key` VARCHAR(255) NULL,
    `cloudinary_api_secret` VARCHAR(255) NULL,
    `resend_api_key` VARCHAR(255) NULL,
    `resend_email` VARCHAR(255) NULL,
    `mail_host` VARCHAR(255) NULL,
    `mail_port` INT NULL,
    `mail_username` VARCHAR(255) NULL,
    `mail_password` VARCHAR(255) NULL,
    `send_grid_api_key` VARCHAR(255) NULL,
    `send_grid_username` VARCHAR(255) NULL,
    `mailgun_api_key` VARCHAR(255) NULL,
    `mailgun_domain` VARCHAR(255) NULL,
    `mailgun_username` VARCHAR(255) NULL,
    `mail_provider` ENUM('SMTP','EXCHANGE','SENDGRID','RESEND','MAILGUN','AMAZON_SES','POSTMARK','OTHER') NULL,
    `phone_provider` ENUM('TWILIO','VONAGE','OTHER') NULL,
    PRIMARY KEY (`id`),
    KEY `idx_businesses_owner_user_id` (`owner_user_id`),
    CONSTRAINT `fk_businesses_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
