CREATE TABLE `contacts` (
    `id` VARCHAR(24) NOT NULL,
    `created_at` DATETIME(6) NULL,
    `updated_at` DATETIME(6) NULL,
    `business_id` VARCHAR(24) NOT NULL,
    `tag_id` VARCHAR(24) NOT NULL,
    `type` ENUM('PERSONAL','COMPANY') NOT NULL,
    `first_name` VARCHAR(255) NOT NULL,
    `last_name` VARCHAR(255) NOT NULL,
    `surname` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(255) NOT NULL,
    `mobile_phone` VARCHAR(255) NULL,
    `email` VARCHAR(255) NOT NULL,
    `birthday` VARCHAR(255) NULL,
    `occupation` VARCHAR(255) NULL,
    `tax_code` VARCHAR(255) NULL,
    `website` VARCHAR(255) NULL,
    `facebook` VARCHAR(255) NULL,
    `instagram` VARCHAR(255) NULL,
    `zalo` VARCHAR(255) NULL,
    `identity_card` VARCHAR(255) NULL,
    `identity_issued_on` DATE NULL,
    `identity_issued_at` VARCHAR(255) NULL,
    `insurance_number` VARCHAR(255) NULL,
    `note` VARCHAR(255) NULL,
    `address_1` VARCHAR(255) NULL,
    `address_2` VARCHAR(255) NULL,
    `country` VARCHAR(255) NULL,
    `zip_code` VARCHAR(255) NULL,
    PRIMARY KEY (`id`),
    KEY `idx_contacts_business_id` (`business_id`),
    KEY `idx_contacts_tag_id` (`tag_id`),
    CONSTRAINT `fk_contacts_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`),
    CONSTRAINT `fk_contacts_tag` FOREIGN KEY (`tag_id`) REFERENCES `contact_tags` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
