CREATE TABLE `leads` (
    `id` VARCHAR(24) NOT NULL,
    `created_at` DATETIME(6) NULL,
    `updated_at` DATETIME(6) NULL,
    `contact_id` VARCHAR(24) NOT NULL,
    `source` ENUM('WEBSITE','LANDING_PAGE','CONTACT_FORM','LIVE_CHAT','CHATBOT','MOBILE_APP','PHONE_CALL','EMAIL','SMS','WHATSAPP','FACEBOOK','INSTAGRAM','LINKEDIN','TIKTOK','YOUTUBE','X_TWITTER','ZALO','GOOGLE_ORGANIC','BING_ORGANIC','OTHER_SEARCH_ENGINE','GOOGLE_ADS','FACEBOOK_ADS','INSTAGRAM_ADS','LINKEDIN_ADS','TIKTOK_ADS','YOUTUBE_ADS','DISPLAY_ADS','RETARGETING_ADS','REFERRAL','CUSTOMER_REFERRAL','PARTNER_REFERRAL','EMPLOYEE_REFERRAL','PARTNER','AFFILIATE','RESELLER','DISTRIBUTOR','EVENT','TRADE_SHOW','CONFERENCE','SEMINAR','WEBINAR','NETWORKING','WALK_IN','STORE_VISIT','QR_CODE','DIRECT_MAIL','COLD_CALL','COLD_EMAIL','OUTBOUND_SALES','MARKETPLACE','API','THIRD_PARTY_INTEGRATION','IMPORT','CSV_IMPORT','OTHER','UNKNOWN') NOT NULL,
    `status` ENUM('NEW','ASSIGNED','CONTACT_ATTEMPTED','CONTACTED','ENGAGED','QUALIFIED','NURTURING','ON_HOLD','UNQUALIFIED','DISQUALIFIED','CONVERTED','LOST','DUPLICATE','INVALID','DO_NOT_CONTACT') NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `uk_leads_contact_id` UNIQUE (`contact_id`),
    CONSTRAINT `fk_leads_contact` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
