CREATE TABLE `calendar_bookings` (
    `id` VARCHAR(24) NOT NULL,
    `created_at` DATETIME(6) NULL,
    `updated_at` DATETIME(6) NULL,
    `business_id` VARCHAR(24) NOT NULL,
    `service_staff_id` VARCHAR(24) NULL,
    `correspondent_id` VARCHAR(24) NULL,
    `contact_id` VARCHAR(24) NOT NULL,
    `booking_start_date` DATETIME(6) NOT NULL,
    `booking_end_date` DATETIME(6) NOT NULL,
    `status` ENUM('WAITING','BOOKED','COMPLETED','CANCELLED','ABSENT','ARRIVED','IN_ROOM','BOUGHT_SERVICE') NOT NULL,
    `cancel_reason` VARCHAR(255) NULL,
    `not_attending_reason` VARCHAR(255) NULL,
    `complaint_reason` VARCHAR(255) NULL,
    PRIMARY KEY (`id`),
    KEY `idx_calendar_bookings_business_id` (`business_id`),
    KEY `idx_calendar_bookings_service_staff_id` (`service_staff_id`),
    KEY `idx_calendar_bookings_correspondent_id` (`correspondent_id`),
    KEY `idx_calendar_bookings_contact_id` (`contact_id`),
    CONSTRAINT `fk_calendar_bookings_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`),
    CONSTRAINT `fk_calendar_bookings_service_staff` FOREIGN KEY (`service_staff_id`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_calendar_bookings_correspondent` FOREIGN KEY (`correspondent_id`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_calendar_bookings_contact` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
