CREATE TABLE `payroll_items` (
    `id` VARCHAR(24) NOT NULL,
    `created_at` DATETIME(6) NULL,
    `updated_at` DATETIME(6) NULL,
    `payroll_period_id` VARCHAR(24) NOT NULL,
    `business_id` VARCHAR(24) NOT NULL,
    `user_id` VARCHAR(24) NOT NULL,
    `base_salary` INT NOT NULL,
    `total_allowances` DOUBLE NOT NULL,
    `total_bonuses` DOUBLE NOT NULL,
    `total_deductions` DOUBLE NOT NULL,
    `tax_amount` DOUBLE NOT NULL,
    `insurance_amount` DOUBLE NOT NULL,
    `net_salary` DOUBLE NOT NULL,
    `worked_days` INT NULL,
    `absent_days` INT NULL,
    `late_days` INT NULL,
    `unpaid_leave_days` INT NULL,
    `status` ENUM('DRAFT','PROCESSING','APPROVED','PAID','CANCELLED') NOT NULL,
    `approver_id` VARCHAR(24) NULL,
    `paid_at` DATETIME(6) NULL,
    PRIMARY KEY (`id`),
    KEY `idx_payroll_items_payroll_period_id` (`payroll_period_id`),
    KEY `idx_payroll_items_business_id` (`business_id`),
    KEY `idx_payroll_items_user_id` (`user_id`),
    KEY `idx_payroll_items_approver_id` (`approver_id`),
    CONSTRAINT `fk_payroll_items_payroll_period` FOREIGN KEY (`payroll_period_id`) REFERENCES `payroll_periods` (`id`),
    CONSTRAINT `fk_payroll_items_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`),
    CONSTRAINT `fk_payroll_items_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_payroll_items_approver` FOREIGN KEY (`approver_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
