CREATE TABLE `medias` (
    `id` VARCHAR(24) NOT NULL,
    `created_at` DATETIME(6) NULL,
    `updated_at` DATETIME(6) NULL,
    `business_id` VARCHAR(24) NOT NULL,
    `owner_id` VARCHAR(24) NOT NULL,
    `storage_key` VARCHAR(1024) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `type` ENUM('FILE','FOLDER') NOT NULL,
    `parent_id` VARCHAR(24) NULL,
    `size` BIGINT NULL,
    `mime_type` VARCHAR(255) NOT NULL,
    `extension` VARCHAR(255) NOT NULL,
    `status` ENUM('ACTIVE','TRASHED') NOT NULL,
    `deleted_at` DATETIME(6) NULL,
    PRIMARY KEY (`id`),
    KEY `idx_medias_business_id` (`business_id`),
    KEY `idx_medias_owner_id` (`owner_id`),
    KEY `idx_medias_parent_id` (`parent_id`),
    KEY `idx_medias_type` (`type`),
    KEY `idx_medias_status` (`status`),
    KEY `idx_medias_created_at` (`created_at`),
    CONSTRAINT `fk_medias_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`),
    CONSTRAINT `fk_medias_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_medias_parent` FOREIGN KEY (`parent_id`) REFERENCES `medias` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
